### ISSUE TITLE
Release of TinyLlama models

### ISSUE THREAD

**Issue by tongyao-zhu** [HKUNLP/STRING#2]
Hi,

Thanks for your wonderful work! I wonder if there is a plan to release the pretrained TinyLlama models with 2k and 4k context sizes, so that we can reproduce Figure 2? 

Thanks in advance!

**Comment by ChenxinAn-fdu** [comment]
Hi! Due to the policy of ByteDance cluster,  we are not permitted to download model weights.  You can use the pretraining code from the [Tinyllama project](https://github.com/jzhang38/TinyLlama). It should reproduce the results.

`Modifications`: (1) replacing the tokenizer with the llama3.1 tokenizer, and the evaluation code can be found [here](https://github.com/HKUNLP/STRING/tree/main/niah). (2) Peiyuan's Tinyllama has a context window of 2048. You can enlarge the block_size in the [config file](https://github.com/jzhang38/TinyLlama/blob/main/lit_gpt/config.py) to 4096 to support a training length of 4096.

**Comment by tongyao-zhu** [comment]
Ok, I understand. Thank you!
