### ISSUE TITLE
Figure 2 (b) Why does the position frequency increase with the Effective length?

### ISSUE THREAD

**Issue by wnma3mz** [HKUNLP/STRING#3]
Great project.

When I read Figure 2(b) of the paper, I found it a little strange. 

<img width="407" alt="image" src="https://github.com/user-attachments/assets/7770d281-5f96-4b46-9965-e6690a895145">

Intuitively, the position frequency should decrease as the effective length increases, as shown in Figure 1 (a) or Figure 3.

<img width="276" alt="image" src="https://github.com/user-attachments/assets/5c6ac6b9-f61d-4ae5-86e6-2a65bb3501dc">

Or what am I getting wrong? Looking forward to your reply.

**Comment by wnma3mz** [comment]
Maybe i got it, it's a `relative position`.

**Comment by wnma3mz** [comment]
I got it. Fig.2. describes **the amount of tokens** required to reach the corresponding `position frequency` of an `effective length`.

**Comment by ChenxinAn-fdu** [comment]
Hahaha, it is really a bit confusing here.

In Figure 2(a), we plot the change in effective length with **the number of tokens**. However, Figure 2(b) illustrates how many times position `n` appears during training when tinyllama reaches an effective length of `n`. For example, the two models achieve an effective length of 1024, the frequency of position 1024 occurring is around 100 billion times.

Position frequency necessarily increases with more training tokens. In Figure 1(a), it depicts the distribution of position frequencies after training on the entire 627 billion tokens from SlimPajama. Larger positions appears fewer times (based on the relative position matrix). In Figure 1, the x-axis only means position and data length instead of  the model's effective length (there is no training procedure here).

**Comment by wnma3mz** [comment]
Thank you for your patient response. The explanation is pretty clear.
